export const movieList = [
    {
      adult: false,
      backdrop_path: "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
      genre_ids: [27],
      id: 938614,
      original_language: "en",
      original_title: "Late Night with the Devil",
      overview:
        "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
      popularity: 598.016,
      poster_path:
        "https://image.tmdb.org/t/p/original/u3YQJctMzFN2wAvnkmXy41bXhFv.jpg",
      release_date: "2024-03-19",
      title: "Late Night with the Devil",
      video: false,
      vote_average: 7.325,
      vote_count: 257,
    },
    {
      adult: false,
      backdrop_path: "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
      genre_ids: [18, 36],
      id: 872585,
      original_language: "en",
      original_title: "Oppenheimer",
      overview:
        "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
      popularity: 589.967,
      poster_path:
        "https://image.tmdb.org/t/p/original/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      release_date: "2023-07-19",
      title: "Oppenheimer",
      video: false,
      vote_average: 8.11,
      vote_count: 7819,
    },
    {
      adult: false,
      backdrop_path: "/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg",
      genre_ids: [18, 10749],
      id: 937287,
      original_language: "en",
      original_title: "Challengers",
      overview:
        'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
      popularity: 574.924,
      poster_path:
        "https://image.tmdb.org/t/p/original/H6vke7zGiuLsz4v4RPeReb9rsv.jpg",
      release_date: "2024-04-18",
      title: "Challengers",
      video: false,
      vote_average: 7.463,
      vote_count: 229,
    },
    {
      adult: false,
      backdrop_path: "/rVJfabCz1ViynQCEz54MRqdZig1.jpg",
      genre_ids: [16, 878, 28],
      id: 1155089,
      original_language: "en",
      original_title: "Justice League: Crisis on Infinite Earths Part One",
      overview:
        "Death is coming. Worse than death: oblivion. Not just for our Earth, but for everyone, everywhere, in every universe! Against this ultimate destruction, the mysterious Monitor has gathered the greatest team of Super Heroes ever assembled. But what can the combined might of Superman, Wonder Woman, Batman, The Flash, Green Lantern and hundreds of Super Heroes from multiple Earths even do to save all of reality from an unstoppable antimatter armageddon?!",
      popularity: 570.756,
      poster_path:
        "https://image.tmdb.org/t/p/original/zR6C66EDklgTPLHRSmmMt5878MR.jpg",
      release_date: "2024-01-08",
      title: "Justice League: Crisis on Infinite Earths Part One",
      video: false,
      vote_average: 7.641,
      vote_count: 191,
    },
    {
      adult: false,
      backdrop_path: "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
      genre_ids: [878, 12, 28],
      id: 653346,
      original_language: "en",
      original_title: "Kingdom of the Planet of the Apes",
      overview:
        "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
      popularity: 558.557,
      poster_path:
        "https://image.tmdb.org/t/p/original/zhyLLcwtvfNiFXDSZ2c5vOxLq2p.jpg",
      release_date: "2024-05-08",
      title: "Kingdom of the Planet of the Apes",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/dcnSWFCtk4b2aIzkhq6IDbzoIf1.jpg",
      genre_ids: [28, 35],
      id: 942047,
      original_language: "en",
      original_title: "Outsource",
      overview:
        "A police chief hires an old friend, who is an international spy, to help him search for a wanted suspect in the Philippines. When the chief dies, all evidence points towards the spy, and he must go to extremes to defend himself.",
      popularity: 558.256,
      poster_path:
        "https://image.tmdb.org/t/p/original/zIAF0UXtCJTJOYNYWiBfyifaaOi.jpg",
      release_date: "2022-01-18",
      title: "Outsource",
      video: false,
      vote_average: 2.3,
      vote_count: 11,
    },
    {
      adult: false,
      backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
      genre_ids: [878, 12],
      id: 438631,
      original_language: "en",
      original_title: "Dune",
      overview:
        "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
      popularity: 532.362,
      poster_path:
        "https://image.tmdb.org/t/p/original/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
      release_date: "2021-09-15",
      title: "Dune",
      video: false,
      vote_average: 7.791,
      vote_count: 11443,
    },
    {
      adult: false,
      backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
      genre_ids: [28, 80, 53],
      id: 385687,
      original_language: "en",
      original_title: "Fast X",
      overview:
        "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
      popularity: 519.832,
      poster_path:
        "https://image.tmdb.org/t/p/original/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
      release_date: "2023-05-17",
      title: "Fast X",
      video: false,
      vote_average: 7.127,
      vote_count: 5095,
    },
    {
      adult: false,
      backdrop_path: "/cIztAxDn3H8JylRaJwiHHpkGe53.jpg",
      genre_ids: [10751, 35, 16],
      id: 1239146,
      original_language: "en",
      original_title: "Woody Woodpecker Goes to Camp",
      overview:
        "After getting kicked out of the forest, Woody thinks he's found a forever home at Camp Woo Hoo — until an inspector threatens to shut down the camp.",
      popularity: 508.871,
      poster_path:
        "https://image.tmdb.org/t/p/original/mMnzNYvpqLLLdgF5TMmXfuy6wzx.jpg",
      release_date: "2024-04-12",
      title: "Woody Woodpecker Goes to Camp",
      video: false,
      vote_average: 6.845,
      vote_count: 100,
    },
    {
      adult: false,
      backdrop_path: "/atPlFdUrQl2U9MtUwujrrjnQHBA.jpg",
      genre_ids: [28, 80, 18, 53],
      id: 654739,
      original_language: "ko",
      original_title: "발신제한",
      overview:
        "On his way to work, a bank manager receives an anonymous call claiming there's a bomb under his car seat, and if anyone exits the car, it will explode unless he can pay a ransom.",
      popularity: 500.059,
      poster_path:
        "https://image.tmdb.org/t/p/original/y2Aimt8isimtigec3e4kB2G9FMR.jpg",
      release_date: "2021-06-23",
      title: "Hard Hit",
      video: false,
      vote_average: 7.7,
      vote_count: 174,
    },
    {
      adult: false,
      backdrop_path: "/9c0lHTXRqDBxeOToVzRu0GArSne.jpg",
      genre_ids: [878, 28],
      id: 935271,
      original_language: "en",
      original_title: "After the Pandemic",
      overview:
        "Set in a post-apocalyptic world where a global airborne pandemic has wiped out 90% of the Earth's population and only the young and immune have endured as scavengers. For Ellie and Quinn, the daily challenges to stay alive are compounded when they become hunted by the merciless Stalkers.",
      popularity: 468.95,
      poster_path:
        "https://image.tmdb.org/t/p/original/p1LbrdJ53dGfEhRopG71akfzOVu.jpg",
      release_date: "2022-03-01",
      title: "After the Pandemic",
      video: false,
      vote_average: 4.798,
      vote_count: 57,
    },
    {
      adult: false,
      backdrop_path: "/kvJZLS607m1xVtEE8w95gmQ6MHE.jpg",
      genre_ids: [27],
      id: 1015303,
      original_language: "en",
      original_title: "Elevator Game",
      overview:
        "Follows socially awkward teenager Ryan, who discovers that the night his sister disappeared she had played ‘The Elevator Game’ — a ritual conducted in an elevator in which players attempt to travel to another dimension using a set of rules that can be found online. Ignoring warnings, he resolves to follow and find her.",
      popularity: 456.908,
      poster_path:
        "https://image.tmdb.org/t/p/original/a4Zb13jow8RqJkYFgCUSdmzJCWq.jpg",
      release_date: "2023-07-12",
      title: "Elevator Game",
      video: false,
      vote_average: 4.663,
      vote_count: 52,
    },
    {
      adult: false,
      backdrop_path: "/deLWkOLZmBNkm8p16igfapQyqeq.jpg",
      genre_ids: [14, 28, 12],
      id: 763215,
      original_language: "en",
      original_title: "Damsel",
      overview:
        "A young woman's marriage to a charming prince turns into a fierce fight for survival when she's offered up as a sacrifice to a fire-breathing dragon.",
      popularity: 454.741,
      poster_path:
        "https://image.tmdb.org/t/p/original/AgHbB9DCE9aE57zkHjSmseszh6e.jpg",
      release_date: "2024-03-07",
      title: "Damsel",
      video: false,
      vote_average: 7.138,
      vote_count: 1703,
    },
    {
      adult: false,
      backdrop_path: "/en971MEXui9diirXlogOrPKmsEn.jpg",
      genre_ids: [28, 12, 35],
      id: 293660,
      original_language: "en",
      original_title: "Deadpool",
      overview:
        "The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
      popularity: 451.34,
      poster_path:
        "https://image.tmdb.org/t/p/original/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg",
      release_date: "2016-02-09",
      title: "Deadpool",
      video: false,
      vote_average: 7.612,
      vote_count: 29801,
    },
  
    {
      adult: false,
      backdrop_path: "/yY76zq9XSuJ4nWyPDuwkdV7Wt0c.jpg",
      genre_ids: [28, 53, 878],
      id: 577922,
      original_language: "en",
      original_title: "Tenet",
      overview:
        "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
      popularity: 439.434,
      poster_path:
        "https://image.tmdb.org/t/p/original/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
      release_date: "2020-08-22",
      title: "Tenet",
      video: false,
      vote_average: 7.183,
      vote_count: 9331,
    },
  
    {
      adult: false,
      backdrop_path: "/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
      genre_ids: [80, 9648, 53],
      id: 414906,
      original_language: "en",
      original_title: "The Batman",
      overview:
        "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
      popularity: 428.959,
      poster_path:
        "https://image.tmdb.org/t/p/original/74xTEgt7R36Fpooo50r9T25onhq.jpg",
      release_date: "2022-03-01",
      title: "The Batman",
      video: false,
      vote_average: 7.685,
      vote_count: 9494,
    },
  
    {
      adult: false,
      backdrop_path: "/qAzYK4YPSWDc7aa4R43LcwRIAyb.jpg",
      genre_ids: [28, 12, 878],
      id: 299537,
      original_language: "en",
      original_title: "Captain Marvel",
      overview:
        "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.",
      popularity: 419.732,
      poster_path:
        "https://image.tmdb.org/t/p/original/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
      release_date: "2019-03-06",
      title: "Captain Marvel",
      video: false,
      vote_average: 6.825,
      vote_count: 15226,
    },
  
    {
      adult: false,
      backdrop_path: "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
      genre_ids: [80, 53, 18],
      id: 475557,
      original_language: "en",
      original_title: "Joker",
      overview:
        "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
      popularity: 428.407,
      poster_path:
        "https://image.tmdb.org/t/p/original/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
      release_date: "2019-10-01",
      title: "Joker",
      video: false,
      vote_average: 8.162,
      vote_count: 24494,
    },
  
    {
      adult: false,
      backdrop_path: "/6iUNJZymJBMXXriQyFZfLAKnjO6.jpg",
      genre_ids: [28, 12, 14],
      id: 297762,
      original_language: "en",
      original_title: "Wonder Woman",
      overview:
        "An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict.",
      popularity: 393.794,
      poster_path:
        "https://image.tmdb.org/t/p/original/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg",
      release_date: "2017-05-30",
      title: "Wonder Woman",
      video: false,
      vote_average: 7.229,
      vote_count: 19475,
    },
    {
      adult: false,
      backdrop_path: "/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg",
      genre_ids: [28, 12, 878],
      id: 284053,
      original_language: "en",
      original_title: "Thor: Ragnarok",
      overview:
        "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of a powerful new threat, the ruthless Hela.",
      popularity: 393.367,
      poster_path:
        "https://image.tmdb.org/t/p/original/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
      release_date: "2017-10-02",
      title: "Thor: Ragnarok",
      video: false,
      vote_average: 7.592,
      vote_count: 20157,
    },
    {
      adult: false,
      backdrop_path: "/lA6KdSkCTxwzvqzPqxch997RabQ.jpg",
      genre_ids: [28, 53, 80],
      id: 560016,
      original_language: "en",
      original_title: "Monkey Man",
      overview:
        "Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.",
      popularity: 356.255,
      poster_path:
        "https://image.tmdb.org/t/p/original/4lhR4L2vzzjl68P1zJyCH755Oz4.jpg",
      release_date: "2024-04-03",
      title: "Monkey Man",
      video: false,
      vote_average: 7.22,
      vote_count: 270,
    },
    {
      adult: false,
      backdrop_path: "/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg",
      genre_ids: [28, 53, 10752],
      id: 969492,
      original_language: "en",
      original_title: "Land of Bad",
      overview:
        "When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.",
      popularity: 331.589,
      poster_path:
        "https://image.tmdb.org/t/p/original/h3jYanWMEJq6JJsCopy1h7cT2Hs.jpg",
      release_date: "2024-01-25",
      title: "Land of Bad",
      video: false,
      vote_average: 7.257,
      vote_count: 670,
    },
    {
      adult: false,
      backdrop_path: "/6dpnthrofbqWmvapUyvqCrkdHG.jpg",
      genre_ids: [28, 53, 878],
      id: 218,
      original_language: "en",
      original_title: "The Terminator",
      overview:
        'In the post-apocalyptic future, reigning tyrannical supercomputers teleport a cyborg assassin known as the "Terminator" back to 1984 to kill Sarah Connor, whose unborn son is destined to lead insurgents against 21st century mechanical hegemony. Meanwhile, the human-resistance movement dispatches a lone warrior to safeguard Sarah. Can he stop the virtually indestructible killing machine?',
      popularity: 422.567,
      poster_path:
        "https://image.tmdb.org/t/p/original/qvktm0BHcnmDpul4Hz01GIazWPr.jpg",
      release_date: "1984-10-26",
      title: "The Terminator",
      video: false,
      vote_average: 7.662,
      vote_count: 12481,
    },
    {
      adult: false,
      backdrop_path: "/9X7YweCJw3q8Mcf6GadxReFEksM.jpg",
      genre_ids: [28, 18, 878],
      id: 263115,
      original_language: "en",
      original_title: "Logan",
      overview:
        "In the near future, a weary Logan cares for an ailing Professor X in a hideout on the Mexican border. But Logan's attempts to hide from the world and his legacy are upended when a young mutant arrives, pursued by dark forces.",
      popularity: 412.05,
      poster_path:
        "https://image.tmdb.org/t/p/original/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
      release_date: "2017-02-28",
      title: "Logan",
      video: false,
      vote_average: 7.817,
      vote_count: 18638,
    },
    {
      adult: false,
      backdrop_path: "/2C3CdVzINUm5Cm1lrbT2uiRstwX.jpg",
      genre_ids: [28, 14, 10752],
      id: 856289,
      original_language: "zh",
      original_title: "封神第一部：朝歌风云",
      overview:
        "Based on the most well-known classical fantasy novel of China, Fengshenyanyi, the trilogy is a magnificent eastern high fantasy epic that recreates the prolonged mythical wars between humans, immortals and monsters, which happened more than three thousand years ago.",
      popularity: 331.726,
      poster_path:
        "https://image.tmdb.org/t/p/original/ccJpK0rqzhQeP7Mrs2uKqObFY4L.jpg",
      release_date: "2023-07-20",
      title: "Creation of the Gods I: Kingdom of Storms",
      video: false,
      vote_average: 7.032,
      vote_count: 234,
    },
    {
      adult: false,
      backdrop_path: "/4qCqAdHcNKeAHcK8tJ8wNJZa9cx.jpg",
      genre_ids: [12, 28, 878],
      id: 11,
      original_language: "en",
      original_title: "Star Wars",
      overview:
        "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
      popularity: 424.405,
      poster_path:
        "https://image.tmdb.org/t/p/original/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
      release_date: "1977-05-25",
      title: "Star Wars",
      video: false,
      vote_average: 8.203,
      vote_count: 19932,
    },
    {
      adult: false,
      backdrop_path: "/8K9qHeM6G6QjQN0C5XKFGvK5lzM.jpg",
      genre_ids: [28, 878],
      id: 603,
      original_language: "en",
      original_title: "The Matrix",
      overview:
        "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
      popularity: 404.5,
      poster_path:
        "https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
      release_date: "1999-03-31",
      title: "The Matrix",
      video: false,
      vote_average: 8.214,
      vote_count: 24810,
    },
    {
      adult: false,
      backdrop_path: "/yF1eOkaYvwiORauRCPWznV9xVvi.jpg",
      genre_ids: [28, 12, 878],
      id: 298618,
      original_language: "en",
      original_title: "The Flash",
      overview:
        "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
      popularity: 402.05,
      poster_path:
        "https://image.tmdb.org/t/p/original/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
      release_date: "2023-06-13",
      title: "The Flash",
      video: false,
      vote_average: 6.744,
      vote_count: 3849,
    },
    {
      adult: false,
      backdrop_path: "/pDKFL1zcHzEpmz4MJA5JJnRbJeD.jpg",
      genre_ids: [27, 53, 18],
      id: 405774,
      original_language: "en",
      original_title: "Bird Box",
      overview:
        "Five years after an ominous unseen presence drives most of society to suicide, a survivor and her two children make a desperate bid to reach safety.",
      popularity: 397.036,
      poster_path:
        "https://image.tmdb.org/t/p/original/rGfGfgL2pEPCfhIvqHXieXFn7gp.jpg",
      release_date: "2018-12-13",
      title: "Bird Box",
      video: false,
      vote_average: 6.844,
      vote_count: 9558,
    },
    {
      adult: false,
      backdrop_path: "/w4pRLYYbhHn3sh9kqRgPZM6GjyS.jpg",
      genre_ids: [878, 12, 28],
      id: 609681,
      original_language: "en",
      original_title: "The Marvels",
      overview:
        "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.",
      popularity: 371.385,
      poster_path:
        "https://image.tmdb.org/t/p/original/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
      release_date: "2023-11-08",
      title: "The Marvels",
      video: false,
      vote_average: 6.171,
      vote_count: 2240,
    },
    {
      adult: false,
      backdrop_path: "/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
      genre_ids: [35, 12],
      id: 346698,
      original_language: "en",
      original_title: "Barbie",
      overview:
        "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
      popularity: 382.182,
      poster_path:
        "https://image.tmdb.org/t/p/original/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
      release_date: "2023-07-19",
      title: "Barbie",
      video: false,
      vote_average: 7.071,
      vote_count: 8126,
    },
    {
      adult: false,
      backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
      genre_ids: [12, 18, 878],
      id: 157336,
      original_language: "en",
      original_title: "Interstellar",
      overview:
        "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
      popularity: 388.917,
      poster_path:
        "https://image.tmdb.org/t/p/original/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      release_date: "2014-11-05",
      title: "Interstellar",
      video: false,
      vote_average: 8.433,
      vote_count: 34210,
    },
    {
      adult: false,
      backdrop_path: "/7lmBufEG7P7Y1HClYK3gCxYrkgS.jpg",
      genre_ids: [12, 28, 878],
      id: 10138,
      original_language: "en",
      original_title: "Iron Man 2",
      overview:
        "With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James 'Rhodey' Rhodes at his side, must forge new alliances – and confront powerful enemies.",
      popularity: 379.208,
      poster_path:
        "https://image.tmdb.org/t/p/original/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg",
      release_date: "2010-04-28",
      title: "Iron Man 2",
      video: false,
      vote_average: 6.839,
      vote_count: 20392,
    },
    {
      adult: false,
      backdrop_path: "/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg",
      genre_ids: [28, 12, 878],
      id: 284054,
      original_language: "en",
      original_title: "Black Panther",
      overview:
        "King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.",
      popularity: 375.667,
      poster_path:
        "https://image.tmdb.org/t/p/original/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
      release_date: "2018-02-13",
      title: "Black Panther",
      video: false,
      vote_average: 7.385,
      vote_count: 21617,
    },
    {
      adult: false,
      backdrop_path: "/yyFc8Iclt2jxPmLztbP617xXllT.jpg",
      genre_ids: [35, 10751, 14],
      id: 787699,
      original_language: "en",
      original_title: "Wonka",
      overview:
        "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
      popularity: 355.997,
      poster_path:
        "https://image.tmdb.org/t/p/original/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
      release_date: "2023-12-06",
      title: "Wonka",
      video: false,
      vote_average: 7.19,
      vote_count: 2898,
    },
    {
      adult: false,
      backdrop_path: "/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg",
      genre_ids: [27, 53, 35],
      id: 1111873,
      original_language: "en",
      original_title: "Abigail",
      overview:
        "After a group of would-be criminals kidnap the 12 year old ballerina daughter of a powerful underworld figure, all they have to do to collect a $50 million ransom is watch the girl overnight. In an isolated mansion, the captors start to dwindle, one by one, and they discover, to their mounting horror, that they’re locked inside with no normal little girl.",
      popularity: 327.603,
      poster_path:
        "https://image.tmdb.org/t/p/original/5Uq8P6MPj9Ppsns5t82AiCiUaWE.jpg",
      release_date: "2024-04-18",
      title: "Abigail",
      video: false,
      vote_average: 6.886,
      vote_count: 79,
    },
    {
      adult: false,
      backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
      genre_ids: [28, 53, 18],
      id: 866398,
      original_language: "en",
      original_title: "The Beekeeper",
      overview:
        "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
      popularity: 317.917,
      poster_path:
        "https://image.tmdb.org/t/p/original/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
      release_date: "2024-01-08",
      title: "The Beekeeper",
      video: false,
      vote_average: 7.449,
      vote_count: 2193,
    },
    {
      adult: false,
      backdrop_path: "/cgo3OmF84touDrrLkQ1DQ3MRFyO.jpg",
      genre_ids: [18, 53],
      id: 1700,
      original_language: "en",
      original_title: "Misery",
      overview:
        "After stalking and saving the life of her favorite fiction author in a car accident, his  manic obsessor holds him captive in her remote Colorado home then forces him to write back to life the popular literary character he killed off.",
      popularity: 374.207,
      poster_path:
        "https://image.tmdb.org/t/p/original/23Y65uWaVMpqfbZTN3CT0aei4D5.jpg",
      release_date: "1990-11-30",
      title: "Misery",
      video: false,
      vote_average: 7.8,
      vote_count: 4415,
    },
    {
      adult: false,
      backdrop_path: "/csGprKcRxt7SDpsrKiwxpgLdEsx.jpg",
      genre_ids: [878, 28, 12, 53],
      id: 16320,
      original_language: "en",
      original_title: "Serenity",
      overview:
        "When the renegade crew of Serenity agrees to hide a fugitive on their ship, they find themselves in an action-packed battle between the relentless military might of a totalitarian regime who will destroy anything – or anyone – to get the girl back and the bloodthirsty creatures who roam the uncharted areas of space. But... the greatest danger of all may be on their ship.",
      popularity: 354.609,
      poster_path:
        "https://image.tmdb.org/t/p/original/ckDo5vnRKehJ2qu8U95c7QcvGUm.jpg",
      release_date: "2005-09-25",
      title: "Serenity",
      video: false,
      vote_average: 7.377,
      vote_count: 3336,
    },
    {
      adult: false,
      backdrop_path: "/hdHIjZxq3SWFqpAz4NFhdbud0iz.jpg",
      genre_ids: [27, 878],
      id: 348,
      original_language: "en",
      original_title: "Alien",
      overview:
        "During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.",
      popularity: 364.31,
      poster_path:
        "https://image.tmdb.org/t/p/original/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
      release_date: "1979-05-25",
      title: "Alien",
      video: false,
      vote_average: 8.152,
      vote_count: 13879,
    },
    {
      adult: false,
      backdrop_path: "/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
      genre_ids: [16, 10751, 35, 14],
      id: 508947,
      original_language: "en",
      original_title: "Turning Red",
      overview:
        "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
      popularity: 380.859,
      poster_path:
        "https://image.tmdb.org/t/p/original/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
      release_date: "2022-03-10",
      title: "Turning Red",
      video: false,
      vote_average: 7.391,
      vote_count: 4917,
    },
    {
      adult: false,
      backdrop_path: "/wUp0bUXaveR40ikBhDgWwNTijuD.jpg",
      genre_ids: [28, 9648, 53],
      id: 1181548,
      original_language: "en",
      original_title: "Heart of the Hunter",
      overview:
        "A retired assassin is pulled back into action when his friend uncovers a dangerous conspiracy at the heart of the South African government.",
      popularity: 316.305,
      poster_path:
        "https://image.tmdb.org/t/p/original/n726fdyL1dGwt15bY7Nj3XOXc4Q.jpg",
      release_date: "2024-03-28",
      title: "Heart of the Hunter",
      video: false,
      vote_average: 5.899,
      vote_count: 79,
    },
    {
      adult: false,
      backdrop_path: "/cjRUhKyt2Jo3V1KNzc5tpPNfccG.jpg",
      genre_ids: [878, 28, 12],
      id: 320288,
      original_language: "en",
      original_title: "Dark Phoenix",
      overview:
        "The X-Men face their most formidable and powerful foe when one of their own, Jean Grey, starts to spiral out of control. During a rescue mission in outer space, Jean is nearly killed when she's hit by a mysterious cosmic force. Once she returns home, this force not only makes her infinitely more powerful, but far more unstable. The X-Men must now band together to save her soul and battle aliens that want to use Grey's new abilities to rule the galaxy.",
      popularity: 383.044,
      poster_path:
        "https://image.tmdb.org/t/p/original/cCTJPelKGLhALq3r51A9uMonxKj.jpg",
      release_date: "2019-06-05",
      title: "Dark Phoenix",
      video: false,
      vote_average: 5.978,
      vote_count: 6222,
    },
    {
      adult: false,
      backdrop_path: "/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
      genre_ids: [878, 10749, 35],
      id: 792307,
      original_language: "en",
      original_title: "Poor Things",
      overview:
        "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
      popularity: 322.807,
      poster_path:
        "https://image.tmdb.org/t/p/original/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
      release_date: "2023-12-07",
      title: "Poor Things",
      video: false,
      vote_average: 7.794,
      vote_count: 3227,
    },
    {
      adult: false,
      backdrop_path: "/8lBViysvNJBPkl6zG1LVAaW3qhj.jpg",
      genre_ids: [28, 12, 53],
      id: 206647,
      original_language: "en",
      original_title: "Spectre",
      overview:
        "A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.",
      popularity: 363.694,
      poster_path:
        "https://image.tmdb.org/t/p/original/zj8ongFhtWNsVlfjOGo8pSr7PQg.jpg",
      release_date: "2015-10-26",
      title: "Spectre",
      video: false,
      vote_average: 6.541,
      vote_count: 10202,
    },
    {
      adult: false,
      backdrop_path: "/w5IDXtifKntw0ajv2co7jFlTQDM.jpg",
      genre_ids: [878, 9648, 12],
      id: 62,
      original_language: "en",
      original_title: "2001: A Space Odyssey",
      overview:
        "Humanity finds a mysterious object buried beneath the lunar surface and sets off to find its origins with the help of HAL 9000, the world's most advanced super computer.",
      popularity: 341.701,
      poster_path:
        "https://image.tmdb.org/t/p/original/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg",
      release_date: "1968-04-02",
      title: "2001: A Space Odyssey",
      video: false,
      vote_average: 8.076,
      vote_count: 11056,
    },
    {
      adult: false,
      backdrop_path: "/e3gVl1gnxEFKLTF6pn6KRqUPi9K.jpg",
      genre_ids: [10749, 18],
      id: 1127166,
      original_language: "it",
      original_title: "Fabbricante di lacrime",
      overview:
        "Adopted together after a tough childhood in an orphanage, Nica and Rigel realize that unexpected but irresistible feelings pull them together.",
      popularity: 312.808,
      poster_path:
        "https://image.tmdb.org/t/p/original/uoBHsxSgfc3PQsSn98RfnbePHOy.jpg",
      release_date: "2024-04-03",
      title: "The Tearsmith",
      video: false,
      vote_average: 6.477,
      vote_count: 485,
    },
    {
      adult: false,
      backdrop_path: "/3P52oz9HPQWxcwHOwxtyrVV1LKi.jpg",
      genre_ids: [28, 35, 12],
      id: 383498,
      original_language: "en",
      original_title: "Deadpool 2",
      overview:
        "Wisecracking mercenary Deadpool battles the evil and powerful Cable and other bad guys to save a boy's life.",
      popularity: 320.786,
      poster_path:
        "https://image.tmdb.org/t/p/original/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
      release_date: "2018-05-10",
      title: "Deadpool 2",
      video: false,
      vote_average: 7.488,
      vote_count: 17010,
    },
    {
      adult: false,
      backdrop_path: "/oMiKHO3H5RixfLsiU5Vumhlp5sj.jpg",
      genre_ids: [80, 10749, 53],
      id: 948549,
      original_language: "en",
      original_title: "Love Lies Bleeding",
      overview:
        "Reclusive gym manager Lou falls hard for Jackie, an ambitious bodybuilder headed through town to Las Vegas in pursuit of her dream. But their love ignites violence, pulling them deep into the web of Lou’s criminal family.",
      popularity: 477.088,
      poster_path:
        "https://image.tmdb.org/t/p/original/p7jyFWiLyHPttqYBFAlLJwtYTYH.jpg",
      release_date: "2024-03-08",
      title: "Love Lies Bleeding",
      video: false,
      vote_average: 7.045,
      vote_count: 99,
    },
    {
      adult: false,
      backdrop_path: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
      genre_ids: [28, 878, 12],
      id: 27205,
      original_language: "en",
      original_title: "Inception",
      overview:
        "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
      popularity: 382.253,
      poster_path:
        "https://image.tmdb.org/t/p/original/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
      release_date: "2010-07-15",
      title: "Inception",
      video: false,
      vote_average: 8.367,
      vote_count: 35633,
    },
    {
      adult: false,
      backdrop_path: "/kK9v1wclQxug6ZUJucD4DTaHgVF.jpg",
      genre_ids: [18],
      id: 1366,
      original_language: "en",
      original_title: "Rocky",
      overview:
        "An uneducated collector for a Philadelphia loan shark is given a once-in-a-lifetime opportunity to fight against the world heavyweight boxing champion.",
      popularity: 322.212,
      poster_path:
        "https://image.tmdb.org/t/p/original/cqxg1CihGR5ge0i1wYXr4Rdeppu.jpg",
      release_date: "1976-11-21",
      title: "Rocky",
      video: false,
      vote_average: 7.787,
      vote_count: 7506,
    },
    {
      adult: false,
      backdrop_path: "/2qluV8y79LnBBHaMpwewCjQ1Htk.jpg",
      genre_ids: [878, 27, 9648],
      id: 126889,
      original_language: "en",
      original_title: "Alien: Covenant",
      overview:
        "The crew of the colony ship Covenant, bound for a remote planet on the far side of the galaxy, discovers what they think is an uncharted paradise but is actually a dark, dangerous world.",
      popularity: 358.148,
      poster_path:
        "https://image.tmdb.org/t/p/original/zecMELPbU5YMQpC81Z8ImaaXuf9.jpg",
      release_date: "2017-05-09",
      title: "Alien: Covenant",
      video: false,
      vote_average: 6.104,
      vote_count: 8165,
    },
    {
      adult: false,
      backdrop_path: "/gG9fTyDL03fiKnOpf2tr01sncnt.jpg",
      genre_ids: [28, 878, 14],
      id: 526896,
      original_language: "en",
      original_title: "Morbius",
      overview:
        "Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.",
      popularity: 365.345,
      poster_path:
        "https://image.tmdb.org/t/p/original/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg",
      release_date: "2022-03-30",
      title: "Morbius",
      video: false,
      vote_average: 6.047,
      vote_count: 4055,
    },
    {
      adult: false,
      backdrop_path: "/8eLXy49T36e0e1YhYvUQOCXNRhm.jpg",
      genre_ids: [14, 18, 9648],
      id: 141,
      original_language: "en",
      original_title: "Donnie Darko",
      overview:
        "After narrowly escaping a bizarre accident, a troubled teenager is plagued by visions of a large bunny rabbit that manipulates him to commit a series of crimes.",
      popularity: 318.462,
      poster_path:
        "https://image.tmdb.org/t/p/original/fhQoQfejY1hUcwyuLgpBrYs6uFt.jpg",
      release_date: "2001-01-19",
      title: "Donnie Darko",
      video: false,
      vote_average: 7.779,
      vote_count: 11979,
    },
    {
      adult: false,
      backdrop_path: "/9pkZesKMnblFfKxEhQx45YQ2kIe.jpg",
      genre_ids: [27, 53],
      id: 381288,
      original_language: "en",
      original_title: "Split",
      overview:
        "Though Kevin has evidenced 23 personalities to his trusted psychiatrist, Dr. Fletcher, there remains one still submerged who is set to materialize and dominate all the others. Compelled to abduct three teenage girls led by the willful, observant Casey, Kevin reaches a war for survival among all of those contained within him — as well as everyone around him — as the walls between his compartments shatter apart.",
      popularity: 345.629,
      poster_path:
        "https://image.tmdb.org/t/p/original/lli31lYTFpvxVBeFHWoe5PMfW5s.jpg",
      release_date: "2017-01-19",
      title: "Split",
      video: false,
      vote_average: 7.342,
      vote_count: 16838,
    },
    {
      adult: false,
      backdrop_path: "/6aoyUbvu0419XLKLIMoH0TkEicH.jpg",
      genre_ids: [80, 18],
      id: 103,
      original_language: "en",
      original_title: "Taxi Driver",
      overview:
        "A mentally unstable Vietnam War veteran works as a night-time taxi driver in New York City where the perceived decadence and sleaze feed his urge for violent action.",
      popularity: 363.873,
      poster_path:
        "https://image.tmdb.org/t/p/original/ekstpH614fwDX8DUln1a2Opz0N8.jpg",
      release_date: "1976-02-09",
      title: "Taxi Driver",
      video: false,
      vote_average: 8.152,
      vote_count: 11734,
    },
    {
      adult: false,
      backdrop_path: "/YL3GPOiDcNraIJOVDCZsoOBoDy.jpg",
      genre_ids: [878, 28, 12, 53],
      id: 106,
      original_language: "en",
      original_title: "Predator",
      overview:
        "A team of elite commandos on a secret mission in a Central American jungle come to find themselves hunted by an extraterrestrial warrior.",
      popularity: 327.468,
      poster_path:
        "https://image.tmdb.org/t/p/original/k3mW4qfJo6SKqe6laRyNGnbB9n5.jpg",
      release_date: "1987-06-12",
      title: "Predator",
      video: false,
      vote_average: 7.523,
      vote_count: 7685,
    },
    {
      adult: false,
      backdrop_path: "/tZ358Wk4BnOc4FjdGsiexAUvCMH.jpg",
      genre_ids: [27, 53],
      id: 424139,
      original_language: "en",
      original_title: "Halloween",
      overview:
        "Laurie Strode comes to her final confrontation with Michael Myers, the masked figure who has haunted her since she narrowly escaped his killing spree on Halloween night four decades ago.",
      popularity: 315.142,
      poster_path:
        "https://image.tmdb.org/t/p/original/f7JAX5EGk4GgsEnus6OxyzwpFp7.jpg",
      release_date: "2018-10-18",
      title: "Halloween",
      video: false,
      vote_average: 6.552,
      vote_count: 4515,
    },
    {
      adult: false,
      backdrop_path: "/4DUoPZOHdPuROP4nyEIsPaMIiQl.jpg",
      genre_ids: [27, 9648, 53],
      id: 493922,
      original_language: "en",
      original_title: "Hereditary",
      overview:
        "Following the death of Ellen Leigh, the matriarch of their family, her daughter Annie and the rest of the family start to uncover disturbing secrets about their heritage.  Their daily lives are not only impacted, but they also become entangled in a chilling fate from which they cannot escape, driving them to the brink of madness.",
      popularity: 131.593,
      poster_path:
        "https://image.tmdb.org/t/p/original/p9fmuz2Oj3HtEJEqbIwkFGUhVXD.jpg",
      release_date: "2018-06-07",
      title: "Hereditary",
      video: false,
      vote_average: 7.283,
      vote_count: 7271,
    },
    {
      adult: false,
      backdrop_path: "/qLsoHP5ri2xnOxZMp8PBf82rgkY.jpg",
      genre_ids: [10402, 35, 18, 10751],
      id: 49863,
      original_language: "en",
      original_title: "The Singing Nun",
      overview:
        "Belgian nun Sister Ann is sent to another order where she's at first committed to helping troubled souls, like Nichole and little Dominic. When Father Clementi hears Sister Ann's uplifting singing style, he takes her to a talent contest. Sister Ann is signed to a record deal and everyone is listening to her lighthearted songs. She is unprepared for her newfound fame (like appearing on The Ed Sullivan Show) and unwanted side effects, including a wrongful attraction to an old friend.",
      popularity: 94.856,
      poster_path:
        "https://image.tmdb.org/t/p/original/vITreT3v0ofJXchbvtlwB6AjR1Z.jpg",
      release_date: "1966-03-17",
      title: "The Singing Nun",
      video: false,
      vote_average: 5.5,
      vote_count: 17,
    },
    {
      adult: false,
      backdrop_path: "/pgEWI7yGYF0mM5Uf1YxSOHsBkJR.jpg",
      genre_ids: [18, 10749],
      id: 4348,
      original_language: "en",
      original_title: "Pride & Prejudice",
      overview:
        "A story of love and life among the landed English gentry during the Georgian era. Mr. Bennet is a gentleman living in Hertfordshire with his overbearing wife and five daughters, but if he dies their house will be inherited by a distant cousin whom they have never met, so the family's future happiness and security is dependent on the daughters making good marriages.",
      popularity: 109.842,
      poster_path:
        "https://image.tmdb.org/t/p/original/sGjIvtVvTlWnia2zfJfHz81pZ9Q.jpg",
      release_date: "2005-09-16",
      title: "Pride & Prejudice",
      video: false,
      vote_average: 8.08,
      vote_count: 7749,
    },
    {
      adult: false,
      backdrop_path: "/8uYbexsonCUDsfFLNyXkMhV3qfe.jpg",
      genre_ids: [27],
      id: 4488,
      original_language: "en",
      original_title: "Friday the 13th",
      overview:
        "Camp counselors are stalked and murdered by an unknown assailant while trying to reopen a summer camp that was the site of a child's drowning.",
      popularity: 111.286,
      poster_path:
        "https://image.tmdb.org/t/p/original/HzrPn1gEHWixfMOvOehOTlHROo.jpg",
      release_date: "1980-05-09",
      title: "Friday the 13th",
      video: false,
      vote_average: 6.39,
      vote_count: 2768,
    },
    {
      adult: false,
      backdrop_path: "/m4c1V53pQ4Z1Jk6rC0Ve3OTcWqW.jpg",
      genre_ids: [28, 80, 53],
      id: 82675,
      original_language: "en",
      original_title: "Taken 2",
      overview:
        "In Istanbul, retired CIA operative Bryan Mills and his wife are taken hostage by the father of a kidnapper Mills killed while rescuing his daughter.",
      popularity: 113.284,
      poster_path:
        "https://image.tmdb.org/t/p/original/yzAlcuJhpnxRPjaj7AHBRbNPQCJ.jpg",
      release_date: "2012-09-27",
      title: "Taken 2",
      video: false,
      vote_average: 6.345,
      vote_count: 6401,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [14],
      id: 298191,
      original_language: "cn",
      original_title: "聊齋花弄月",
      overview:
        "Very seldom shown erotic story of a cuckolded husband who departs his home and unwittingly becomes included with not one, but two, alluring ghosts. [Rim movies Catalog] Mandy and his spouse (that's right, Mandy is a man) will be an uncommon few under any conditions. Mandy fools around with young women while his spouse is within the home, nevertheless the wife isn't bothered a lot. She is just considering in the job she's offered Mandy, which is .... to frequently check with the neighborhood brothelkeeper, and find away if she's found guys with incredibly difficult manhoods. How hard ? Complicated enough to punch an opening in a sack of grain (ouch !). And one more thing. Mandy and his wife are ghosts. Of course, this means you will find people who are seeking to exorcise them. In between residential disputes and pursued exorcisms, there's acres of nudity and lots of sex.",
      popularity: 104.25,
      poster_path:
        "https://image.tmdb.org/t/p/original/jqcoVHn983shN0ChOfO18BWQqpZ.jpg",
      release_date: "1991-05-03",
      title: "Liao Zhai - Home for the Intimate Ghosts",
      video: false,
      vote_average: 7.4,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: "/9qokUngA9fAgBy7skSyZj2irOfR.jpg",
      genre_ids: [12, 28, 53, 878],
      id: 563,
      original_language: "en",
      original_title: "Starship Troopers",
      overview:
        'Set in the future, the story follows a young soldier named Johnny Rico and his exploits in the Mobile Infantry. Rico\'s military career progresses from recruit to non-commissioned officer and finally to officer against the backdrop of an interstellar war between mankind and an arachnoid species known as "the Bugs".',
      popularity: 99.987,
      poster_path:
        "https://image.tmdb.org/t/p/original/cxCmv23O7p3hyHwqoktHYkZcGsY.jpg",
      release_date: "1997-11-07",
      title: "Starship Troopers",
      video: false,
      vote_average: 7.1,
      vote_count: 4671,
    },
    {
      adult: false,
      backdrop_path: "/2uSCHUsmzb6KkQPFSxBQ7bgfJLE.jpg",
      genre_ids: [28, 878, 27],
      id: 345940,
      original_language: "en",
      original_title: "The Meg",
      overview:
        "A deep sea submersible pilot revisits his past fears in the Mariana Trench, and accidentally unleashes the seventy foot ancestor of the Great White Shark believed to be extinct.",
      popularity: 103.228,
      poster_path:
        "https://image.tmdb.org/t/p/original/eyWICPcxOuTcDDDbTMOZawoOn8d.jpg",
      release_date: "2018-08-09",
      title: "The Meg",
      video: false,
      vote_average: 6.258,
      vote_count: 7373,
    },
    {
      adult: false,
      backdrop_path: "/7jBnqB4KK9cZJSMPtRYRDjpACVE.jpg",
      genre_ids: [18, 10752, 36, 27],
      id: 40339,
      original_language: "it",
      original_title: "Casa privata per le SS",
      overview:
        "Top Nazi officials, intent on rooting out traitors and those in the military who may be plotting to overthrow Adolf Hitler, recruit and train a group of beautiful prostitutes whose mission is to use any means necessary to uncover plots against the Fuhrer.",
      popularity: 96.96,
      poster_path:
        "https://image.tmdb.org/t/p/original/mrPhJFdf62KC8nLcS1aYR5rKgfN.jpg",
      release_date: "1977-01-20",
      title: "Private House of the SS",
      video: false,
      vote_average: 5.045,
      vote_count: 33,
    },
    {
      adult: false,
      backdrop_path: "/7JhsJxNmdW0y4IyNrHy10cECrAz.jpg",
      genre_ids: [35],
      id: 109418,
      original_language: "en",
      original_title: "Grown Ups 2",
      overview:
        "Lenny has relocated his family back to the small town where he and his friends grew up. This time around, the grown ups are the ones learning lessons from their kids on a day notoriously full of surprises—the last day of school.",
      popularity: 78.474,
      poster_path:
        "https://image.tmdb.org/t/p/original/hT6ijOtjtYrnyDhN7VA2QWyGFAm.jpg",
      release_date: "2013-07-11",
      title: "Grown Ups 2",
      video: false,
      vote_average: 6.125,
      vote_count: 4124,
    },
    {
      adult: false,
      backdrop_path: "/gMVdhfQ7q9DFHhDkehrququjGPd.jpg",
      genre_ids: [35, 80, 18, 36],
      id: 487558,
      original_language: "en",
      original_title: "BlacKkKlansman",
      overview:
        "Colorado Springs, late 1970s. Ron Stallworth, an African American police officer, and Flip Zimmerman, his Jewish colleague, run an undercover operation to infiltrate the Ku Klux Klan.",
      popularity: 86.467,
      poster_path:
        "https://image.tmdb.org/t/p/original/8jxqAvSDoneSKRczaK8v9X5gqBp.jpg",
      release_date: "2018-08-09",
      title: "BlacKkKlansman",
      video: false,
      vote_average: 7.5,
      vote_count: 7309,
    },
    {
      adult: false,
      backdrop_path: "/fjl3gXybEOg65MDIlpGXlF7iKEl.jpg",
      genre_ids: [18],
      id: 271045,
      original_language: "it",
      original_title: "La moglie di mio padre",
      overview:
        "A wealthy man suffers from impotence whenever he tries to make love to his wife. Since Viagara hadn't been invented yet, his swinging liberal doctor instead recommends a strong dose of infidelity. Before long he is rolling in the hay with a young lovely and needless to say his impotence problem is cured (it's amazing that he doesn't have a heart attack though). His wife is a little bitter, however, and decides to embark on her own affair. And if you're wondering with whom, well, just look at the title.",
      popularity: 98.668,
      poster_path:
        "https://image.tmdb.org/t/p/original/g7YUdF1Iv0f4ddnfq3Dkqs9woTq.jpg",
      release_date: "1976-08-04",
      title: "Confessions of a Frustrated Housewife",
      video: false,
      vote_average: 7.0,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: "/8UiZP1dTIPRYkIcwR84zZTwgKpZ.jpg",
      genre_ids: [28, 53, 878],
      id: 59967,
      original_language: "en",
      original_title: "Looper",
      overview:
        "In the year 2044, time travel has not yet been invented but in 30 years it will have been. When the mob wants to get rid of someone, they will send their target into the past where a looper, a hired gun, like Joe is waiting to mop up. Joe is getting rich and life is good until the day the mob decides to close the loop, sending back Joe's future self for assassination.",
      popularity: 92.184,
      poster_path:
        "https://image.tmdb.org/t/p/original/sNjL6SqErDBE8OUZlrDLkexfsCj.jpg",
      release_date: "2012-09-26",
      title: "Looper",
      video: false,
      vote_average: 6.882,
      vote_count: 9893,
    },
    {
      adult: false,
      backdrop_path: "/dK12GIdhGP6NPGFssK2Fh265jyr.jpg",
      genre_ids: [28, 35, 80],
      id: 512195,
      original_language: "en",
      original_title: "Red Notice",
      overview:
        "An Interpol-issued Red Notice is a global alert to hunt and capture the world's most wanted. But when a daring heist brings together the FBI's top profiler and two rival criminals, there's no telling what will happen.",
      popularity: 98.949,
      poster_path:
        "https://image.tmdb.org/t/p/original/lAXONuqg41NwUMuzMiFvicDET9Y.jpg",
      release_date: "2021-11-04",
      title: "Red Notice",
      video: false,
      vote_average: 6.777,
      vote_count: 5500,
    },
    {
      adult: false,
      backdrop_path: "/m5dA4JZsj78EBTa2D6imWOAebwB.jpg",
      genre_ids: [35],
      id: 4247,
      original_language: "en",
      original_title: "Scary Movie",
      overview:
        "A familiar-looking group of teenagers find themselves being stalked by a more-than-vaguely recognizable masked killer! As the victims begin to pile up and the laughs pile on, none of your favorite scary movies escape the razor-sharp satire of this outrageously funny parody!",
      popularity: 97.168,
      poster_path:
        "https://image.tmdb.org/t/p/original/lRQiJXETkCnVVurHmglNvMXrZOx.jpg",
      release_date: "2000-07-07",
      title: "Scary Movie",
      video: false,
      vote_average: 6.354,
      vote_count: 6663,
    },
    {
      adult: false,
      backdrop_path: "/8knaRrDd1FM1pbSLaViEQSxodi5.jpg",
      genre_ids: [18, 53],
      id: 441282,
      original_language: "en",
      original_title: "Night Hunter",
      overview:
        "A Minnesota police officer crosses paths with a committed and tireless vigilante as he follows the trail of a ruthless predator responsible for several abductions and murders.",
      popularity: 103.415,
      poster_path:
        "https://image.tmdb.org/t/p/original/vVYU0x9FRpiJNX7c54ciFnRBVYG.jpg",
      release_date: "2019-08-29",
      title: "Night Hunter",
      video: false,
      vote_average: 6.496,
      vote_count: 789,
    },
    {
      adult: false,
      backdrop_path: "/4dcx4odNyL7IQ8c6vb6oYkjk9rg.jpg",
      genre_ids: [36, 18],
      id: 798612,
      original_language: "en",
      original_title: "Shirley",
      overview:
        "Shirley Chisholm makes a trailblazing run for the 1972 Democratic presidential nomination after becoming the first Black woman elected to Congress.",
      popularity: 101.97,
      poster_path:
        "https://image.tmdb.org/t/p/original/ooo4D4kyZyFee5aiNfwZ43oKOkc.jpg",
      release_date: "2024-03-21",
      title: "Shirley",
      video: false,
      vote_average: 6.761,
      vote_count: 45,
    },
    {
      adult: false,
      backdrop_path: "/vaArQHq1lHFNppoJlMlv30Gs2fQ.jpg",
      genre_ids: [27, 53, 9648],
      id: 433808,
      original_language: "en",
      original_title: "The Ritual",
      overview:
        "A group of college friends reunite for a trip to the forest, but encounter a menacing presence in the woods that's stalking them.",
      popularity: 106.389,
      poster_path:
        "https://image.tmdb.org/t/p/original/9022CYEGqYETCeXN1oE3uwYJWub.jpg",
      release_date: "2017-10-11",
      title: "The Ritual",
      video: false,
      vote_average: 6.233,
      vote_count: 2820,
    },
    {
      adult: false,
      backdrop_path: "/jZP7baK3QLZCeZx3AqdMjjg1Vv1.jpg",
      genre_ids: [18, 53, 80],
      id: 979,
      original_language: "fr",
      original_title: "Irréversible",
      overview:
        "A woman’s lover and her ex-boyfriend take justice into their own hands after she becomes the victim of a rapist. Because some acts can’t be undone. Because man is an animal. Because the desire for vengeance is a natural impulse. Because most crimes remain unpunished.",
      popularity: 90.882,
      poster_path:
        "https://image.tmdb.org/t/p/original/rxeDxo8FvZpLu6iplNpxdtAVnfu.jpg",
      release_date: "2002-05-22",
      title: "Irreversible",
      video: false,
      vote_average: 7.2,
      vote_count: 2749,
    },
    {
      adult: false,
      backdrop_path: "/oOROXoQ402tHgK6NowmMUSLffkW.jpg",
      genre_ids: [53, 9648, 18],
      id: 452832,
      original_language: "en",
      original_title: "Serenity",
      overview:
        "The quiet life of Baker Dill, a fishing boat captain who lives on the isolated Plymouth Island, where he spends his days obsessed with capturing an elusive tuna while fighting his personal demons, is interrupted when someone from his past comes to him searching for help.",
      popularity: 93.359,
      poster_path:
        "https://image.tmdb.org/t/p/original/hgWAcic93phg4DOuQ8NrsgQWiqu.jpg",
      release_date: "2019-01-24",
      title: "Serenity",
      video: false,
      vote_average: 5.454,
      vote_count: 1476,
    },
  ];
  